backend:
  name: github
  repo: Edubmstr/test_project # Path to your GitHub repository
  # optional, defaults to master
  branch: decap_cms_test

media_folder: "/images" # Location where files will be stored in the repo
public_folder: "/images" # The src attribute for uploaded media

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    identifier_field: "path"
    label: "Page" # Used in the UI
    folder: "src/content/pages" # The path to the folder where the documents are stored
    slug: "{{path}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", hidden: true }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "photo_gallery"
    identifier_field: "path"
    label: "Foto Gallerie" # Used in the UI
    folder: "src/content/photo_gallery" # The path to the folder where the documents are stored
    slug: "{{path}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", hidden: true }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false, multiple: false }
      - label: Bilder
        name: photos
        widget: list
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Photo, name: photo, widget: image}
      - { label: "Body", name: "body", widget: "markdown", required: false }
